### ISSUE TITLE
mkfrogfs.py directory filters are broken

### ISSUE THREAD

**Issue by jkent** [jkent/esp32-espfs#50]
Currently it is not possible to match just a directory and apply filters on it.  You have to glob it like the following to apply to all descendants:

```yaml
filters:
  'path/to/folder_name*':
    - discard
  ```

You should be able to just do the following:

```yaml
filters:
  'path/to/folder_name':
    - discard
 ```

...but this is currently broken.
